import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SeenHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
            <div className="container p-10">
                <h1 className="text-center text-3xl">SEENHUB</h1>
            </div>
            <div className="container p-10">
                <ol>
                    <li className="flex space-x-6">
                        <a href="">MUSIC</a>
                        <a href="">MOVIE</a>
                        <a href="">BOOK</a>
                    </li>
                </ol>
            </div>
        </header>

        <main>{children}</main>

        <footer className="container p-10">seenhub v.0.1</footer>

      </body>
    </html>
  );
}
