import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Avatar from "boring-avatars";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SeenHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
            <div className="container flex justify-between p-10">
                <Link href="/" className="text-center text-3xl font-bold">SEENHUB</Link>
                <Avatar name="Julia" colors={["#ff0000", "#0000ff"]} variant="beam" size={40} />
            </div>
            <div className="container pl-10">
                <ol>
                    <li className="flex space-x-6 font-bold">
                        <Link href="/music">MUSIC</Link>
                        <Link href="/movie">MOVIE</Link>
                        <Link href="/book">BOOK</Link>
                    </li>
                </ol>
            </div>
        </header>

        <main>{children}</main>

        <footer className="container p-10">seenhub v.0.1</footer>

      </body>
    </html>
  );
}
